# Generated by Django 4.2.7 on 2023-12-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia', models.CharField(max_length=100)),
                ('informacion', models.CharField(max_length=200)),
            ],
        ),
    ]
