# Generated by Django 4.2.7 on 2023-12-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticiavideojuego_delete_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiavideojuego',
            name='foto',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
    ]
