# Generated by Django 4.2.7 on 2023-12-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_noticiavideojuego_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiavideojuego',
            name='foto',
        ),
    ]
